class NonEnglishWords:
    ABBREVIATIONS = {
        "$": " dollar ",
        "€": " euro ",
        "4ao": "for adults only",
        "a.m": "before midday",
        "a3": "anytime anywhere anyplace",
        "aamof": "as a matter of fact",
        "acct": "account",
        "adih": "another day in hell",
        "afaic": "as far as i am concerned",
        "afaict": "as far as i can tell",
        "afaik": "as far as i know",
        "afair": "as far as i remember",
        "afk": "away from keyboard",
        "app": "application",
        "approx": "approximately",
        "apps": "applications",
        "asap": "as soon as possible",
        "asl": "age:sex:location",
        "atk": "at the keyboard",
        "ave.": "avenue",
        "aymm": "are you my mother",
        "ayor": "at your own risk",
        "b&b": "bed and breakfast",
        "b+b": "bed and breakfast",
        "b.c": "before christ",
        "b2b": "business to business",
        "b2c": "business to customer",
        "b4": "before",
        "b4n": "bye for now",
        "b@u": "back at you",
        "bae": "before anyone else",
        "bak": "back at keyboard",
        "bbbg": "bye bye be good",
        "bbc": "british broadcasting corporation",
        "bbias": "be back in a second",
        "bbl": "be back later",
        "bbs": "be back soon",
        "be4": "before",
        "bfn": "bye for now",
        "blvd": "boulevard",
        "bout": "about",
        "brb": "be right back",
        "bros": "brothers",
        "brt": "be right there",
        "bsaaw": "big smile and a wink",
        "btw": "by the way",
        "bwl": "bursting with laughter",
        "c/o": "care of",
        "cet": "central european time",
        "cf": "compare",
        "cia": "central intelligence agency",
        "csl": "can not stop laughing",
        "cu": "see you",
        "cul8r": "see you later",
        "cv": "curriculum vitae",
        "cwot": "complete waste of time",
        "cya": "see you",
        "cyt": "see you tomorrow",
        "dae": "does anyone else",
        "dbmib": "do not bother me i am busy",
        "diy": "do it yourself",
        "dm": "direct message",
        "dwh": "during work hours",
        "e123": "easy as one two three",
        "eet": "eastern european time",
        "eg": "example",
        "embm": "early morning business meeting",
        "encl": "enclosed",
        "encl.": "enclosed",
        "etc": "and so on",
        "faq": "frequently asked questions",
        "fawc": "for anyone who cares",
        "fb": "facebook",
        "fc": "fingers crossed",
        "fig": "figure",
        "fimh": "forever in my heart",
        "ft.": "feet",
        "ft": "featuring",
        "ftl": "for the loss",
        "ftw": "for the win",
        "fwiw": "for what it is worth",
        "fyi": "for your information",
        "g9": "genius",
        "gahoy": "get a hold of yourself",
        "gal": "get a life",
        "gcse": "general certificate of secondary education",
        "gfn": "gone for now",
        "gg": "good game",
        "gl": "good luck",
        "glhf": "good luck have fun",
        "gmt": "greenwich mean time",
        "gmta": "great minds think alike",
        "gn": "good night",
        "g.o.a.t": "greatest of all time",
        "goat": "greatest of all time",
        "goi": "get over it",
        "gps": "global positioning system",
        "gr8": "great",
        "gratz": "congratulations",
        "gyal": "girl",
        "h&c": "hot and cold",
        "hp": "horsepower",
        "hr": "hour",
        "hrh": "his royal highness",
        "ht": "height",
        "ibrb": "i will be right back",
        "ic": "i see",
        "icq": "i seek you",
        "icymi": "in case you missed it",
        "idc": "i do not care",
        "idgadf": "i do not give a damn fuck",
        "idgaf": "i do not give a fuck",
        "idk": "i do not know",
        "ie": "that is",
        "i.e": "that is",
        "ifyp": "i feel your pain",
        "ig": "instagram",
        "iirc": "if i remember correctly",
        "ilu": "i love you",
        "ily": "i love you",
        "imho": "in my humble opinion",
        "imo": "in my opinion",
        "imu": "i miss you",
        "iow": "in other words",
        "irl": "in real life",
        "j4f": "just for fun",
        "jic": "just in case",
        "jk": "just kidding",
        "jsyk": "just so you know",
        "l8r": "later",
        "lb": "pound",
        "lbs": "pounds",
        "ldr": "long distance relationship",
        "lmao": "laugh my ass off",
        "lmfao": "laugh my fucking ass off",
        "lol": "laughing out loud",
        "ltd": "limited",
        "ltns": "long time no see",
        "m8": "mate",
        "mf": "motherfucker",
        "mfs": "motherfuckers",
        "mfw": "my face when",
        "mofo": "motherfucker",
        "mph": "miles per hour",
        "mr": "mister",
        "mrw": "my reaction when",
        "ms": "miss",
        "mte": "my thoughts exactly",
        "nagi": "not a good idea",
        "nbc": "national broadcasting company",
        "nbd": "not big deal",
        "nfs": "not for sale",
        "ngl": "not going to lie",
        "nhs": "national health service",
        "nrn": "no reply necessary",
        "nsfl": "not safe for life",
        "nsfw": "not safe for work",
        "nth": "nice to have",
        "nvr": "never",
        "nyc": "new york city",
        "oc": "original content",
        "og": "original",
        "ohp": "overhead projector",
        "oic": "oh i see",
        "omdb": "over my dead body",
        "omg": "oh my god",
        "omw": "on my way",
        "p.a": "per annum",
        "p.m": "after midday",
        "pm": "prime minister",
        "poc": "people of color",
        "pov": "point of view",
        "pp": "pages",
        "ppl": "people",
        "prw": "parents are watching",
        "ps": "postscript",
        "pt": "point",
        "ptb": "please text back",
        "pto": "please turn over",
        "qpsa": "what happens",
        "ratchet": "rude",
        "rbtl": "read between the lines",
        "rlrt": "real life retweet",
        "rofl": "rolling on the floor laughing",
        "roflol": "rolling on the floor laughing out loud",
        "rotflmao": "rolling on the floor laughing my ass off",
        "rt": "retweet",
        "ruok": "are you ok",
        "sfw": "safe for work",
        "sk8": "skate",
        "smh": "shake my head",
        "sq": "square",
        "srsly": "seriously",
        "ssdd": "same stuff different day",
        "tbh": "to be honest",
        "tbs": "tablespooful",
        "tbsp": "tablespooful",
        "tfw": "that feeling when",
        "thks": "thank you",
        "tho": "though",
        "thx": "thank you",
        "tia": "thanks in advance",
        "til": "today i learned",
        "tl;dr": "too long i did not read",
        "tldr": "too long i did not read",
        "tmb": "tweet me back",
        "tntl": "trying not to laugh",
        "ttyl": "talk to you later",
        "u": "you",
        "u2": "you too",
        "u4e": "yours for ever",
        "utc": "coordinated universal time",
        "w/": "with",
        "w/o": "without",
        "w8": "wait",
        "wassup": "what is up",
        "wb": "welcome back",
        "wtf": "what the fuck",
        "wtg": "way to go",
        "wtpa": "where the party at",
        "wuf": "where are you from",
        "wuzup": "what is up",
        "wywh": "wish you were here",
        "yd": "yard",
        "ygtr": "you got that right",
        "ynk": "you never know",
        "zzz": "sleeping bored and tired"
    }

    NON_ENGLISH_WORDS = {
        "\x89Û_": "",
        "\x89ÛÒ": "",
        "\x89ÛÓ": "",
        "\x89ÛÏ": "",
        "\x89Û÷": "",
        "\x89Ûª": "",
        "\x89Û\x9d": "",
        "å_": "",
        "\x89Û¢": "",
        "\x89Û¢åÊ": "",
        "åÊ": "",
        "åÈ": "",
        "Ì©": "e",
        "å¨": "",
        "åÇ": "",
        "åÀ": "",
        # remove contractions
        "let\x89Ûªs": "let us",
        "let's": "let us",
        "he's": "he is",
        "there's": "there is",
        "we're": "we are",
        "that's": "that is",
        "that\x89Ûªs": "that is",
        "won't": "will not",
        "wont": "will not",
        "they're": "they are",
        "can't": "cannot",
        "cant": "cannot",
        "can\x89Ûªt": "cannot",
        "wasn't": "was not",
        "wasnt": "was not",
        "don't": "do not",
        "dont": "do not",
        "donå«t": "do not",
        "don\x89Ûªt": "do not",
        "didn't": "did not",
        "didnt": "did not",
        "aren't": "are not",
        "isn't": "is not",
        "what's": "what is",
        "haven't": "have not",
        "hasn't": "has not",
        "it's": "it is",
        "it\x89Ûªs": "it is",
        "you're": "you are",
        "you\x89Ûªre": "you are",
        "i'm": "i am",
        "i\x89Ûªm": "i am",
        "shoulda": "should have",
        "shouldn't": "should not",
        "wouldn't": "would not",
        "wouldn\x89Ûªt": "would not",
        "here's": "here is",
        "here\x89Ûªs": "here is",
        "where's": "where is",
        "you've": "you have",
        "you\x89Ûªve": "you have",
        "youve": "you have",
        "couldn't": "could not",
        "we've": "we have",
        "doesn't": "does not",
        "doesn\x89Ûªt": "does not",
        "who's": "who is",
        "i've": "i have",
        "i\x89Ûªve": "i have",
        "y'all": "you all",
        "would've": "would have",
        "it'll": "it will",
        "we'll": "we will",
        "he'll": "he will",
        "weren't": "were not",
        "they'll": "they will",
        "they'd": "they would",
        "they've": "they have",
        "i'd": "i would",
        "I\x89Ûªd": "I would",
        "should've": "should have",
        "we'd": "we would",
        "i'll": "i will",
        "^ill$": "i will",
        "you'll": "you will",
        "you\x89Ûªll": "you will",
        "ain't": "am not",
        "you'd": "you would",
        "could've": "could have",
        "mÌ¼sica": "music",
        "some1": "someone",
        "yrs": "years",
        "hrs": "hours",
        "2morow|2moro": "tomorrow",
        "2day": "today",
        "4got|4gotten": "forget",
        "b-day|bday": "b-day",
        "mother's": "mother",
        "mom's": "mom",
        "dad's": "dad",
        "^[h|a]+$": "haha",
        "lmao|lolz|rofl": "lol",
        "thanx|thnx|thx": "thanks",
        'all[l]+': "all",
        'so[o]+': "so",
        'a[w]+': "awww",
        'why[y]+': "why",
        'way[y]+': "way",
        'will[l]+': "will",
        'oo[o]+h': "ooh",
        'hey[y]+': "hey",
        "boo[o]+m": "boom",
        "co[o]+ld": "cold",
        "goo[o]+d": "good",
        "luckigrrl": "lucky girl",
        "evolvin": "evolving",
        "#": "",
        "n\'t": "not",
        "\'re": " are",
        "\'s": " is",
        "\'d": " would",
        "\'ll": " will",
        "\'t": " not",
        "\'ve": " have",
        "\'m": " am",
        "&gt;": ">",
        "&lt;": "<",
        "&amp;": "&",
        "w/e": "whatever",
        "usagov": "usa government",
        "<3": "love",
        "trfc": "traffic",
    }
